project_name: authdemo
release:
  github:
    owner: aricart
    name: authdemo
  name_template: '{{.Tag}}'
  draft: true
builds:
- main: ./main.go
  ldflags: "-X main.version={{.Tag}}"
  env:
    - CGO_ENABLED=0
  binary: authdemo
  goos:
  - darwin
  - linux
  goarch:
  - amd64

dist: build

archives:
  - id: "authdemo.zip"
    wrap_in_directory: false
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: zip
    files:
      - none*

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

snapshot:
  name_template: 'dev'


